enum SecondModelShipmentStatusType {
  ORDER_SHIPMENT_STATUS_TYPE_ERROR = 0,
  ORDER_SHIPMENT_STATUS_TYPE_CANCELLED = 1,
  ORDER_SHIPMENT_STATUS_TYPE_IN_PREPARATION = 2,
  ORDER_SHIPMENT_STATUS_TYPE_SHIPPED = 3,
  ORDER_SHIPMENT_STATUS_TYPE_IN_TRANSIT = 4,
  ORDER_SHIPMENT_STATUS_TYPE_DELIVERED = 5,
  UNRECOGNIZED = -1,
}
export default SecondModelShipmentStatusType;
