enum SecondModelStatusType {
  ORDER_STATUS_TYPE_ERROR = 0,
  ORDER_STATUS_TYPE_CANCELLED = 1,
  ORDER_STATUS_TYPE_UNORDERED = 2,
  ORDER_STATUS_TYPE_ORDERED = 3,
  ORDER_STATUS_TYPE_CONFIRMED = 4,
  ORDER_STATUS_TYPE_IN_PREPARATION = 5,
  ORDER_STATUS_TYPE_SHIPPING = 6,
  ORDER_STATUS_TYPE_RECEPTION_PROCESSED = 7,
  UNRECOGNIZED = -1,
}
export default SecondModelStatusType;
