enum Shipper {
  SHIPPER_UNKNOWN = 0,
  SHIPPER_TNT = 1,
  SHIPPER_UPS = 2,
  SHIPPER_DHL = 3,
  SHIPPER_FEDEX = 4,
  SHIPPER_CHRONOPOST = 5,
  SHIPPER_COLISSIMO = 6,
  UNRECOGNIZED = -1,
}

export default Shipper;
